<div style="background-color: #B0E0E6;" align="center">

Exercise 3: **Preprocessing** - cleaning and data and scaling the data so the classification accuracy won't get hurt. 
</div>


In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
X,y=load_iris(return_X_y=True)

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)
X_train_scaled

array([[ 1.12373858, -1.35176469,  1.21772384,  0.83487224],
       [ 2.34188338, -1.11870182,  1.83524035,  1.48373668],
       [-0.70347862,  0.97886409, -1.19620433, -1.24149395],
       [-0.94710758,  0.27967545, -1.36461792, -1.24149395],
       [ 1.36736754,  0.27967545,  1.16158598,  1.48373668],
       [-0.33803518, -1.11870182,  0.43179374,  0.05623492],
       [-0.09440622, -0.65257606,  0.26338015,  0.1860078 ],
       [-1.06892206, -0.1864503 , -1.25234219, -1.24149395],
       [ 0.3928517 , -0.1864503 ,  0.54406947,  0.31578069],
       [-0.33803518, -1.81789045,  0.20724228,  0.1860078 ],
       [-1.67799446,  0.27967545, -1.30848006, -1.24149395],
       [ 0.75829514, -0.41951318,  0.37565588,  0.1860078 ],
       [-0.09440622,  1.67805272, -1.0839286 , -1.11172107],
       [ 0.14922274, -0.1864503 ,  0.31951801,  0.44555358],
       [ 0.75829514, -0.65257606,  1.10544811,  1.2241909 ],
       [-0.8252931 ,  0.97886409, -1.25234219, -1.24149395],
       [-0.09440622,  3.

In [11]:
import  numpy as np
(X_train-np.mean(X_train,axis=0))/np.std(X_train,axis=0)  # algorithm for scalor function 

array([[ 1.12373858, -1.35176469,  1.21772384,  0.83487224],
       [ 2.34188338, -1.11870182,  1.83524035,  1.48373668],
       [-0.70347862,  0.97886409, -1.19620433, -1.24149395],
       [-0.94710758,  0.27967545, -1.36461792, -1.24149395],
       [ 1.36736754,  0.27967545,  1.16158598,  1.48373668],
       [-0.33803518, -1.11870182,  0.43179374,  0.05623492],
       [-0.09440622, -0.65257606,  0.26338015,  0.1860078 ],
       [-1.06892206, -0.1864503 , -1.25234219, -1.24149395],
       [ 0.3928517 , -0.1864503 ,  0.54406947,  0.31578069],
       [-0.33803518, -1.81789045,  0.20724228,  0.1860078 ],
       [-1.67799446,  0.27967545, -1.30848006, -1.24149395],
       [ 0.75829514, -0.41951318,  0.37565588,  0.1860078 ],
       [-0.09440622,  1.67805272, -1.0839286 , -1.11172107],
       [ 0.14922274, -0.1864503 ,  0.31951801,  0.44555358],
       [ 0.75829514, -0.65257606,  1.10544811,  1.2241909 ],
       [-0.8252931 ,  0.97886409, -1.25234219, -1.24149395],
       [-0.09440622,  3.

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scale=scaler.transform(X_test)